### PR TITLE
sirius: Update memory parameters for 3GB device.

### PR DESCRIPTION
**Pull request by Abhinav1997**
Sirius had 3 GB RAM last time I checked. :) Thanks @Myself5 for heads up

### CODE REVIEW

**Comment by jerpelea** [comment]
for the moment 3.10 kernel does not boot with all memory enabled on this device
till we fix it 2GB is max

**Comment by Abhinav1997** [comment]
Is this only on sirius or other devices having 3GB RAM?

**Comment by jerpelea** [comment]
8974pro-ab family

**Comment by Abhinav1997** [comment]
Ohk

**Pull request merged**
